# Generated by Django 6.0.1 on 2026-01-10 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaicertificate_chaireview_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chai_varities',
            new_name='chai_varieties',
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chai_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
